<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/thingspect_device.proto

namespace Thingspect\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Device represents a device as stored in the database.
 *
 * Generated from protobuf message <code>thingspect.api.Device</code>
 */
class Device extends \Google\Protobuf\Internal\Message
{
    /**
     * Device ID (UUID).
     *
     * Generated from protobuf field <code>string id = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $id = '';
    /**
     * Organization ID (UUID).
     *
     * Generated from protobuf field <code>string org_id = 2 [json_name = "orgID", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $org_id = '';
    /**
     * Device unique ID.
     *
     * Generated from protobuf field <code>string uniq_id = 3 [json_name = "uniqID", (.validate.rules) = {</code>
     */
    protected $uniq_id = '';
    /**
     * Device name.
     *
     * Generated from protobuf field <code>string name = 4 [(.validate.rules) = {</code>
     */
    protected $name = '';
    /**
     * Device status.
     *
     * Generated from protobuf field <code>.thingspect.api.Status status = 5 [(.validate.rules) = {</code>
     */
    protected $status = 0;
    /**
     * Authentication token (UUID). Will be generated at creation time, but can be updated afterward.
     *
     * Generated from protobuf field <code>string token = 6 [(.validate.rules) = {</code>
     */
    protected $token = '';
    /**
     * Device data payload decoder.
     *
     * Generated from protobuf field <code>.thingspect.api.Decoder decoder = 7;</code>
     */
    protected $decoder = 0;
    /**
     * Device tags. Nested tags should be delimited by '/'.
     *
     * Generated from protobuf field <code>repeated string tags = 8 [(.validate.rules) = {</code>
     */
    private $tags;
    /**
     * Device creation timestamp.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 9 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $created_at = null;
    /**
     * Device modification timestamp.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 10 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $updated_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Device ID (UUID).
     *     @type string $org_id
     *           Organization ID (UUID).
     *     @type string $uniq_id
     *           Device unique ID.
     *     @type string $name
     *           Device name.
     *     @type int $status
     *           Device status.
     *     @type string $token
     *           Authentication token (UUID). Will be generated at creation time, but can be updated afterward.
     *     @type int $decoder
     *           Device data payload decoder.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $tags
     *           Device tags. Nested tags should be delimited by '/'.
     *     @type \Google\Protobuf\Timestamp $created_at
     *           Device creation timestamp.
     *     @type \Google\Protobuf\Timestamp $updated_at
     *           Device modification timestamp.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\ThingspectDevice::initOnce();
        parent::__construct($data);
    }

    /**
     * Device ID (UUID).
     *
     * Generated from protobuf field <code>string id = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Device ID (UUID).
     *
     * Generated from protobuf field <code>string id = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Organization ID (UUID).
     *
     * Generated from protobuf field <code>string org_id = 2 [json_name = "orgID", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getOrgId()
    {
        return $this->org_id;
    }

    /**
     * Organization ID (UUID).
     *
     * Generated from protobuf field <code>string org_id = 2 [json_name = "orgID", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setOrgId($var)
    {
        GPBUtil::checkString($var, True);
        $this->org_id = $var;

        return $this;
    }

    /**
     * Device unique ID.
     *
     * Generated from protobuf field <code>string uniq_id = 3 [json_name = "uniqID", (.validate.rules) = {</code>
     * @return string
     */
    public function getUniqId()
    {
        return $this->uniq_id;
    }

    /**
     * Device unique ID.
     *
     * Generated from protobuf field <code>string uniq_id = 3 [json_name = "uniqID", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setUniqId($var)
    {
        GPBUtil::checkString($var, True);
        $this->uniq_id = $var;

        return $this;
    }

    /**
     * Device name.
     *
     * Generated from protobuf field <code>string name = 4 [(.validate.rules) = {</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Device name.
     *
     * Generated from protobuf field <code>string name = 4 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Device status.
     *
     * Generated from protobuf field <code>.thingspect.api.Status status = 5 [(.validate.rules) = {</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Device status.
     *
     * Generated from protobuf field <code>.thingspect.api.Status status = 5 [(.validate.rules) = {</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Thingspect\Api\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Authentication token (UUID). Will be generated at creation time, but can be updated afterward.
     *
     * Generated from protobuf field <code>string token = 6 [(.validate.rules) = {</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Authentication token (UUID). Will be generated at creation time, but can be updated afterward.
     *
     * Generated from protobuf field <code>string token = 6 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * Device data payload decoder.
     *
     * Generated from protobuf field <code>.thingspect.api.Decoder decoder = 7;</code>
     * @return int
     */
    public function getDecoder()
    {
        return $this->decoder;
    }

    /**
     * Device data payload decoder.
     *
     * Generated from protobuf field <code>.thingspect.api.Decoder decoder = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setDecoder($var)
    {
        GPBUtil::checkEnum($var, \Thingspect\Api\Decoder::class);
        $this->decoder = $var;

        return $this;
    }

    /**
     * Device tags. Nested tags should be delimited by '/'.
     *
     * Generated from protobuf field <code>repeated string tags = 8 [(.validate.rules) = {</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Device tags. Nested tags should be delimited by '/'.
     *
     * Generated from protobuf field <code>repeated string tags = 8 [(.validate.rules) = {</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

    /**
     * Device creation timestamp.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 9 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Device creation timestamp.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 9 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Device modification timestamp.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 10 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    public function hasUpdatedAt()
    {
        return isset($this->updated_at);
    }

    public function clearUpdatedAt()
    {
        unset($this->updated_at);
    }

    /**
     * Device modification timestamp.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 10 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

}

