<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/thingspect_datapoint.proto

namespace Thingspect\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * LatestDataPointsResponse is sent in response to a device latest list.
 *
 * Generated from protobuf message <code>thingspect.api.LatestDataPointsResponse</code>
 */
class LatestDataPointsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Data point array, ordered by ascending attribute name.
     *
     * Generated from protobuf field <code>repeated .thingspect.common.DataPoint points = 1;</code>
     */
    private $points;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Thingspect\Common\DataPoint>|\Google\Protobuf\Internal\RepeatedField $points
     *           Data point array, ordered by ascending attribute name.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\ThingspectDatapoint::initOnce();
        parent::__construct($data);
    }

    /**
     * Data point array, ordered by ascending attribute name.
     *
     * Generated from protobuf field <code>repeated .thingspect.common.DataPoint points = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPoints()
    {
        return $this->points;
    }

    /**
     * Data point array, ordered by ascending attribute name.
     *
     * Generated from protobuf field <code>repeated .thingspect.common.DataPoint points = 1;</code>
     * @param array<\Thingspect\Common\DataPoint>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPoints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Thingspect\Common\DataPoint::class);
        $this->points = $arr;

        return $this;
    }

}

