<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/thingspect_alert.proto

namespace Thingspect\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * ListAlertsResponse is sent in response to a device alerts list.
 *
 * Generated from protobuf message <code>thingspect.api.ListAlertsResponse</code>
 */
class ListAlertsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Alert array, ordered by descending created_at timestamp.
     *
     * Generated from protobuf field <code>repeated .thingspect.api.Alert alerts = 1;</code>
     */
    private $alerts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Thingspect\Api\Alert[] $alerts
     *           Alert array, ordered by descending created_at timestamp.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\ThingspectAlert::initOnce();
        parent::__construct($data);
    }

    /**
     * Alert array, ordered by descending created_at timestamp.
     *
     * Generated from protobuf field <code>repeated .thingspect.api.Alert alerts = 1;</code>
     * @return RepeatedField<\Thingspect\Api\Alert>
     */
    public function getAlerts()
    {
        return $this->alerts;
    }

    /**
     * Alert array, ordered by descending created_at timestamp.
     *
     * Generated from protobuf field <code>repeated .thingspect.api.Alert alerts = 1;</code>
     * @param \Thingspect\Api\Alert[] $var
     * @return $this
     */
    public function setAlerts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Thingspect\Api\Alert::class);
        $this->alerts = $arr;

        return $this;
    }

}

