<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/thingspect_org.proto

namespace Thingspect\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Org represents an organization as stored in the database.
 *
 * Generated from protobuf message <code>thingspect.api.Org</code>
 */
class Org extends \Google\Protobuf\Internal\Message
{
    /**
     * Organization ID (UUID).
     *
     * Generated from protobuf field <code>string id = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $id = '';
    /**
     * Organization name.
     *
     * Generated from protobuf field <code>string name = 2 [(.validate.rules) = {</code>
     */
    protected $name = '';
    /**
     * Organization display name. Used anywhere the organization is shown to a user, including web sites and alert sender fields.
     *
     * Generated from protobuf field <code>string display_name = 3 [(.validate.rules) = {</code>
     */
    protected $display_name = '';
    /**
     * Organization email. Used as the 'From' address in email alerts.
     *
     * Generated from protobuf field <code>string email = 4 [(.validate.rules) = {</code>
     */
    protected $email = '';
    /**
     * Organization creation timestamp.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 5 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $created_at = null;
    /**
     * Organization modification timestamp.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 6 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $updated_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Organization ID (UUID).
     *     @type string $name
     *           Organization name.
     *     @type string $display_name
     *           Organization display name. Used anywhere the organization is shown to a user, including web sites and alert sender fields.
     *     @type string $email
     *           Organization email. Used as the 'From' address in email alerts.
     *     @type \Google\Protobuf\Timestamp $created_at
     *           Organization creation timestamp.
     *     @type \Google\Protobuf\Timestamp $updated_at
     *           Organization modification timestamp.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\ThingspectOrg::initOnce();
        parent::__construct($data);
    }

    /**
     * Organization ID (UUID).
     *
     * Generated from protobuf field <code>string id = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Organization ID (UUID).
     *
     * Generated from protobuf field <code>string id = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Organization name.
     *
     * Generated from protobuf field <code>string name = 2 [(.validate.rules) = {</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Organization name.
     *
     * Generated from protobuf field <code>string name = 2 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Organization display name. Used anywhere the organization is shown to a user, including web sites and alert sender fields.
     *
     * Generated from protobuf field <code>string display_name = 3 [(.validate.rules) = {</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->display_name;
    }

    /**
     * Organization display name. Used anywhere the organization is shown to a user, including web sites and alert sender fields.
     *
     * Generated from protobuf field <code>string display_name = 3 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->display_name = $var;

        return $this;
    }

    /**
     * Organization email. Used as the 'From' address in email alerts.
     *
     * Generated from protobuf field <code>string email = 4 [(.validate.rules) = {</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Organization email. Used as the 'From' address in email alerts.
     *
     * Generated from protobuf field <code>string email = 4 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Organization creation timestamp.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 5 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Organization creation timestamp.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 5 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Organization modification timestamp.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 6 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    public function hasUpdatedAt()
    {
        return isset($this->updated_at);
    }

    public function clearUpdatedAt()
    {
        unset($this->updated_at);
    }

    /**
     * Organization modification timestamp.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 6 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

}

