<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/thingspect_rule_alarm.proto

namespace Thingspect\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * TestRuleRequest is sent to test a rule.
 *
 * Generated from protobuf message <code>thingspect.api.TestRuleRequest</code>
 */
class TestRuleRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Data point to test against a rule.
     *
     * Generated from protobuf field <code>.thingspect.common.DataPoint point = 1 [(.google.api.field_behavior) = REQUIRED, (.validate.rules) = {</code>
     */
    protected $point = null;
    /**
     * Rule message to test.
     *
     * Generated from protobuf field <code>.thingspect.api.Rule rule = 2 [(.google.api.field_behavior) = REQUIRED, (.validate.rules) = {</code>
     */
    protected $rule = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Thingspect\Common\DataPoint $point
     *           Data point to test against a rule.
     *     @type \Thingspect\Api\Rule $rule
     *           Rule message to test.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\ThingspectRuleAlarm::initOnce();
        parent::__construct($data);
    }

    /**
     * Data point to test against a rule.
     *
     * Generated from protobuf field <code>.thingspect.common.DataPoint point = 1 [(.google.api.field_behavior) = REQUIRED, (.validate.rules) = {</code>
     * @return \Thingspect\Common\DataPoint|null
     */
    public function getPoint()
    {
        return $this->point;
    }

    public function hasPoint()
    {
        return isset($this->point);
    }

    public function clearPoint()
    {
        unset($this->point);
    }

    /**
     * Data point to test against a rule.
     *
     * Generated from protobuf field <code>.thingspect.common.DataPoint point = 1 [(.google.api.field_behavior) = REQUIRED, (.validate.rules) = {</code>
     * @param \Thingspect\Common\DataPoint $var
     * @return $this
     */
    public function setPoint($var)
    {
        GPBUtil::checkMessage($var, \Thingspect\Common\DataPoint::class);
        $this->point = $var;

        return $this;
    }

    /**
     * Rule message to test.
     *
     * Generated from protobuf field <code>.thingspect.api.Rule rule = 2 [(.google.api.field_behavior) = REQUIRED, (.validate.rules) = {</code>
     * @return \Thingspect\Api\Rule|null
     */
    public function getRule()
    {
        return $this->rule;
    }

    public function hasRule()
    {
        return isset($this->rule);
    }

    public function clearRule()
    {
        unset($this->rule);
    }

    /**
     * Rule message to test.
     *
     * Generated from protobuf field <code>.thingspect.api.Rule rule = 2 [(.google.api.field_behavior) = REQUIRED, (.validate.rules) = {</code>
     * @param \Thingspect\Api\Rule $var
     * @return $this
     */
    public function setRule($var)
    {
        GPBUtil::checkMessage($var, \Thingspect\Api\Rule::class);
        $this->rule = $var;

        return $this;
    }

}

