<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/thingspect_rule_alarm.proto

namespace Thingspect\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * TestRuleResponse is sent in response to a rule test.
 *
 * Generated from protobuf message <code>thingspect.api.TestRuleResponse</code>
 */
class TestRuleResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Result of the rule evaluation.
     *
     * Generated from protobuf field <code>bool result = 1;</code>
     */
    protected $result = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $result
     *           Result of the rule evaluation.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\ThingspectRuleAlarm::initOnce();
        parent::__construct($data);
    }

    /**
     * Result of the rule evaluation.
     *
     * Generated from protobuf field <code>bool result = 1;</code>
     * @return bool
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Result of the rule evaluation.
     *
     * Generated from protobuf field <code>bool result = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkBool($var);
        $this->result = $var;

        return $this;
    }

}

