// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api/thingspect_tag.proto
// Protobuf C++ Version: 5.29.4

#include "api/thingspect_tag.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace thingspect {
namespace api {

inline constexpr ListTagsResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : tags_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ListTagsResponse::ListTagsResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ListTagsResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListTagsResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListTagsResponseDefaultTypeInternal() {}
  union {
    ListTagsResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListTagsResponseDefaultTypeInternal _ListTagsResponse_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR ListTagsRequest::ListTagsRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct ListTagsRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListTagsRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListTagsRequestDefaultTypeInternal() {}
  union {
    ListTagsRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListTagsRequestDefaultTypeInternal _ListTagsRequest_default_instance_;
}  // namespace api
}  // namespace thingspect
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_api_2fthingspect_5ftag_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_api_2fthingspect_5ftag_2eproto = nullptr;
const ::uint32_t
    TableStruct_api_2fthingspect_5ftag_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::thingspect::api::ListTagsRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::thingspect::api::ListTagsResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::thingspect::api::ListTagsResponse, _impl_.tags_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::thingspect::api::ListTagsRequest)},
        {8, -1, -1, sizeof(::thingspect::api::ListTagsResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::thingspect::api::_ListTagsRequest_default_instance_._instance,
    &::thingspect::api::_ListTagsResponse_default_instance_._instance,
};
const char descriptor_table_protodef_api_2fthingspect_5ftag_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\030api/thingspect_tag.proto\022\016thingspect.a"
    "pi\032\034google/api/annotations.proto\"\021\n\017List"
    "TagsRequest\" \n\020ListTagsResponse\022\014\n\004tags\030"
    "\001 \003(\t2m\n\nTagService\022_\n\010ListTags\022\037.things"
    "pect.api.ListTagsRequest\032 .thingspect.ap"
    "i.ListTagsResponse\"\020\202\323\344\223\002\n\022\010/v1/tagsB$Z\""
    "github.com/thingspect/proto/go/apib\006prot"
    "o3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_api_2fthingspect_5ftag_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fapi_2fannotations_2eproto,
};
static ::absl::once_flag descriptor_table_api_2fthingspect_5ftag_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_api_2fthingspect_5ftag_2eproto = {
    false,
    false,
    282,
    descriptor_table_protodef_api_2fthingspect_5ftag_2eproto,
    "api/thingspect_tag.proto",
    &descriptor_table_api_2fthingspect_5ftag_2eproto_once,
    descriptor_table_api_2fthingspect_5ftag_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_api_2fthingspect_5ftag_2eproto::offsets,
    file_level_enum_descriptors_api_2fthingspect_5ftag_2eproto,
    file_level_service_descriptors_api_2fthingspect_5ftag_2eproto,
};
namespace thingspect {
namespace api {
// ===================================================================

class ListTagsRequest::_Internal {
 public:
};

ListTagsRequest::ListTagsRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:thingspect.api.ListTagsRequest)
}
ListTagsRequest::ListTagsRequest(
    ::google::protobuf::Arena* arena,
    const ListTagsRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ListTagsRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:thingspect.api.ListTagsRequest)
}

inline void* ListTagsRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ListTagsRequest(arena);
}
constexpr auto ListTagsRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ListTagsRequest),
                                            alignof(ListTagsRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ListTagsRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ListTagsRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ListTagsRequest::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<ListTagsRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ListTagsRequest::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<ListTagsRequest>(), &ListTagsRequest::ByteSizeLong,
            &ListTagsRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ListTagsRequest, _impl_._cached_size_),
        false,
    },
    &ListTagsRequest::kDescriptorMethods,
    &descriptor_table_api_2fthingspect_5ftag_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ListTagsRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> ListTagsRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::thingspect::api::ListTagsRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata ListTagsRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ListTagsResponse::_Internal {
 public:
};

ListTagsResponse::ListTagsResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:thingspect.api.ListTagsResponse)
}
inline PROTOBUF_NDEBUG_INLINE ListTagsResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::thingspect::api::ListTagsResponse& from_msg)
      : tags_{visibility, arena, from.tags_},
        _cached_size_{0} {}

ListTagsResponse::ListTagsResponse(
    ::google::protobuf::Arena* arena,
    const ListTagsResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ListTagsResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:thingspect.api.ListTagsResponse)
}
inline PROTOBUF_NDEBUG_INLINE ListTagsResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : tags_{visibility, arena},
        _cached_size_{0} {}

inline void ListTagsResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ListTagsResponse::~ListTagsResponse() {
  // @@protoc_insertion_point(destructor:thingspect.api.ListTagsResponse)
  SharedDtor(*this);
}
inline void ListTagsResponse::SharedDtor(MessageLite& self) {
  ListTagsResponse& this_ = static_cast<ListTagsResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ListTagsResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ListTagsResponse(arena);
}
constexpr auto ListTagsResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ListTagsResponse, _impl_.tags_) +
          decltype(ListTagsResponse::_impl_.tags_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(ListTagsResponse), alignof(ListTagsResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ListTagsResponse::PlacementNew_,
                                 sizeof(ListTagsResponse),
                                 alignof(ListTagsResponse));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ListTagsResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ListTagsResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ListTagsResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ListTagsResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ListTagsResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ListTagsResponse>(), &ListTagsResponse::ByteSizeLong,
            &ListTagsResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ListTagsResponse, _impl_._cached_size_),
        false,
    },
    &ListTagsResponse::kDescriptorMethods,
    &descriptor_table_api_2fthingspect_5ftag_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ListTagsResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 44, 2> ListTagsResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::thingspect::api::ListTagsResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string tags = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ListTagsResponse, _impl_.tags_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string tags = 1;
    {PROTOBUF_FIELD_OFFSET(ListTagsResponse, _impl_.tags_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\37\4\0\0\0\0\0\0"
    "thingspect.api.ListTagsResponse"
    "tags"
  }},
};

PROTOBUF_NOINLINE void ListTagsResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:thingspect.api.ListTagsResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.tags_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ListTagsResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ListTagsResponse& this_ = static_cast<const ListTagsResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ListTagsResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ListTagsResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:thingspect.api.ListTagsResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated string tags = 1;
          for (int i = 0, n = this_._internal_tags_size(); i < n; ++i) {
            const auto& s = this_._internal_tags().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "thingspect.api.ListTagsResponse.tags");
            target = stream->WriteString(1, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:thingspect.api.ListTagsResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ListTagsResponse::ByteSizeLong(const MessageLite& base) {
          const ListTagsResponse& this_ = static_cast<const ListTagsResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ListTagsResponse::ByteSizeLong() const {
          const ListTagsResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:thingspect.api.ListTagsResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string tags = 1;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_tags().size());
              for (int i = 0, n = this_._internal_tags().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_tags().Get(i));
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ListTagsResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ListTagsResponse*>(&to_msg);
  auto& from = static_cast<const ListTagsResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:thingspect.api.ListTagsResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_tags()->MergeFrom(from._internal_tags());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ListTagsResponse::CopyFrom(const ListTagsResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:thingspect.api.ListTagsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ListTagsResponse::InternalSwap(ListTagsResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.tags_.InternalSwap(&other->_impl_.tags_);
}

::google::protobuf::Metadata ListTagsResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace api
}  // namespace thingspect
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_api_2fthingspect_5ftag_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
