// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api/thingspect_datapoint.proto
#ifndef GRPC_api_2fthingspect_5fdatapoint_2eproto__INCLUDED
#define GRPC_api_2fthingspect_5fdatapoint_2eproto__INCLUDED

#include "api/thingspect_datapoint.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace thingspect {
namespace api {

// DataPointService contains functions to create and query data points.
class DataPointService final {
 public:
  static constexpr char const* service_full_name() {
    return "thingspect.api.DataPointService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Publish data points via the API. Data points are generated by devices.
    virtual ::grpc::Status PublishDataPoints(::grpc::ClientContext* context, const ::thingspect::api::PublishDataPointsRequest& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncPublishDataPoints(::grpc::ClientContext* context, const ::thingspect::api::PublishDataPointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncPublishDataPointsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsyncPublishDataPoints(::grpc::ClientContext* context, const ::thingspect::api::PublishDataPointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsyncPublishDataPointsRaw(context, request, cq));
    }
    // List all data points for a device in an [end, start) time range, in descending timestamp order. Data points are generated by devices.
    virtual ::grpc::Status ListDataPoints(::grpc::ClientContext* context, const ::thingspect::api::ListDataPointsRequest& request, ::thingspect::api::ListDataPointsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::thingspect::api::ListDataPointsResponse>> AsyncListDataPoints(::grpc::ClientContext* context, const ::thingspect::api::ListDataPointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::thingspect::api::ListDataPointsResponse>>(AsyncListDataPointsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::thingspect::api::ListDataPointsResponse>> PrepareAsyncListDataPoints(::grpc::ClientContext* context, const ::thingspect::api::ListDataPointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::thingspect::api::ListDataPointsResponse>>(PrepareAsyncListDataPointsRaw(context, request, cq));
    }
    // List the latest data point for each of a device's attributes in a [now, start) time range. Data points are generated by devices.
    virtual ::grpc::Status LatestDataPoints(::grpc::ClientContext* context, const ::thingspect::api::LatestDataPointsRequest& request, ::thingspect::api::LatestDataPointsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::thingspect::api::LatestDataPointsResponse>> AsyncLatestDataPoints(::grpc::ClientContext* context, const ::thingspect::api::LatestDataPointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::thingspect::api::LatestDataPointsResponse>>(AsyncLatestDataPointsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::thingspect::api::LatestDataPointsResponse>> PrepareAsyncLatestDataPoints(::grpc::ClientContext* context, const ::thingspect::api::LatestDataPointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::thingspect::api::LatestDataPointsResponse>>(PrepareAsyncLatestDataPointsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Publish data points via the API. Data points are generated by devices.
      virtual void PublishDataPoints(::grpc::ClientContext* context, const ::thingspect::api::PublishDataPointsRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PublishDataPoints(::grpc::ClientContext* context, const ::thingspect::api::PublishDataPointsRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // List all data points for a device in an [end, start) time range, in descending timestamp order. Data points are generated by devices.
      virtual void ListDataPoints(::grpc::ClientContext* context, const ::thingspect::api::ListDataPointsRequest* request, ::thingspect::api::ListDataPointsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListDataPoints(::grpc::ClientContext* context, const ::thingspect::api::ListDataPointsRequest* request, ::thingspect::api::ListDataPointsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // List the latest data point for each of a device's attributes in a [now, start) time range. Data points are generated by devices.
      virtual void LatestDataPoints(::grpc::ClientContext* context, const ::thingspect::api::LatestDataPointsRequest* request, ::thingspect::api::LatestDataPointsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void LatestDataPoints(::grpc::ClientContext* context, const ::thingspect::api::LatestDataPointsRequest* request, ::thingspect::api::LatestDataPointsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncPublishDataPointsRaw(::grpc::ClientContext* context, const ::thingspect::api::PublishDataPointsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsyncPublishDataPointsRaw(::grpc::ClientContext* context, const ::thingspect::api::PublishDataPointsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::thingspect::api::ListDataPointsResponse>* AsyncListDataPointsRaw(::grpc::ClientContext* context, const ::thingspect::api::ListDataPointsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::thingspect::api::ListDataPointsResponse>* PrepareAsyncListDataPointsRaw(::grpc::ClientContext* context, const ::thingspect::api::ListDataPointsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::thingspect::api::LatestDataPointsResponse>* AsyncLatestDataPointsRaw(::grpc::ClientContext* context, const ::thingspect::api::LatestDataPointsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::thingspect::api::LatestDataPointsResponse>* PrepareAsyncLatestDataPointsRaw(::grpc::ClientContext* context, const ::thingspect::api::LatestDataPointsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status PublishDataPoints(::grpc::ClientContext* context, const ::thingspect::api::PublishDataPointsRequest& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncPublishDataPoints(::grpc::ClientContext* context, const ::thingspect::api::PublishDataPointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncPublishDataPointsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsyncPublishDataPoints(::grpc::ClientContext* context, const ::thingspect::api::PublishDataPointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsyncPublishDataPointsRaw(context, request, cq));
    }
    ::grpc::Status ListDataPoints(::grpc::ClientContext* context, const ::thingspect::api::ListDataPointsRequest& request, ::thingspect::api::ListDataPointsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::thingspect::api::ListDataPointsResponse>> AsyncListDataPoints(::grpc::ClientContext* context, const ::thingspect::api::ListDataPointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::thingspect::api::ListDataPointsResponse>>(AsyncListDataPointsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::thingspect::api::ListDataPointsResponse>> PrepareAsyncListDataPoints(::grpc::ClientContext* context, const ::thingspect::api::ListDataPointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::thingspect::api::ListDataPointsResponse>>(PrepareAsyncListDataPointsRaw(context, request, cq));
    }
    ::grpc::Status LatestDataPoints(::grpc::ClientContext* context, const ::thingspect::api::LatestDataPointsRequest& request, ::thingspect::api::LatestDataPointsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::thingspect::api::LatestDataPointsResponse>> AsyncLatestDataPoints(::grpc::ClientContext* context, const ::thingspect::api::LatestDataPointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::thingspect::api::LatestDataPointsResponse>>(AsyncLatestDataPointsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::thingspect::api::LatestDataPointsResponse>> PrepareAsyncLatestDataPoints(::grpc::ClientContext* context, const ::thingspect::api::LatestDataPointsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::thingspect::api::LatestDataPointsResponse>>(PrepareAsyncLatestDataPointsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void PublishDataPoints(::grpc::ClientContext* context, const ::thingspect::api::PublishDataPointsRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) override;
      void PublishDataPoints(::grpc::ClientContext* context, const ::thingspect::api::PublishDataPointsRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListDataPoints(::grpc::ClientContext* context, const ::thingspect::api::ListDataPointsRequest* request, ::thingspect::api::ListDataPointsResponse* response, std::function<void(::grpc::Status)>) override;
      void ListDataPoints(::grpc::ClientContext* context, const ::thingspect::api::ListDataPointsRequest* request, ::thingspect::api::ListDataPointsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void LatestDataPoints(::grpc::ClientContext* context, const ::thingspect::api::LatestDataPointsRequest* request, ::thingspect::api::LatestDataPointsResponse* response, std::function<void(::grpc::Status)>) override;
      void LatestDataPoints(::grpc::ClientContext* context, const ::thingspect::api::LatestDataPointsRequest* request, ::thingspect::api::LatestDataPointsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncPublishDataPointsRaw(::grpc::ClientContext* context, const ::thingspect::api::PublishDataPointsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsyncPublishDataPointsRaw(::grpc::ClientContext* context, const ::thingspect::api::PublishDataPointsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::thingspect::api::ListDataPointsResponse>* AsyncListDataPointsRaw(::grpc::ClientContext* context, const ::thingspect::api::ListDataPointsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::thingspect::api::ListDataPointsResponse>* PrepareAsyncListDataPointsRaw(::grpc::ClientContext* context, const ::thingspect::api::ListDataPointsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::thingspect::api::LatestDataPointsResponse>* AsyncLatestDataPointsRaw(::grpc::ClientContext* context, const ::thingspect::api::LatestDataPointsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::thingspect::api::LatestDataPointsResponse>* PrepareAsyncLatestDataPointsRaw(::grpc::ClientContext* context, const ::thingspect::api::LatestDataPointsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PublishDataPoints_;
    const ::grpc::internal::RpcMethod rpcmethod_ListDataPoints_;
    const ::grpc::internal::RpcMethod rpcmethod_LatestDataPoints_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Publish data points via the API. Data points are generated by devices.
    virtual ::grpc::Status PublishDataPoints(::grpc::ServerContext* context, const ::thingspect::api::PublishDataPointsRequest* request, ::google::protobuf::Empty* response);
    // List all data points for a device in an [end, start) time range, in descending timestamp order. Data points are generated by devices.
    virtual ::grpc::Status ListDataPoints(::grpc::ServerContext* context, const ::thingspect::api::ListDataPointsRequest* request, ::thingspect::api::ListDataPointsResponse* response);
    // List the latest data point for each of a device's attributes in a [now, start) time range. Data points are generated by devices.
    virtual ::grpc::Status LatestDataPoints(::grpc::ServerContext* context, const ::thingspect::api::LatestDataPointsRequest* request, ::thingspect::api::LatestDataPointsResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_PublishDataPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PublishDataPoints() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PublishDataPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PublishDataPoints(::grpc::ServerContext* /*context*/, const ::thingspect::api::PublishDataPointsRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPublishDataPoints(::grpc::ServerContext* context, ::thingspect::api::PublishDataPointsRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListDataPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListDataPoints() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ListDataPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListDataPoints(::grpc::ServerContext* /*context*/, const ::thingspect::api::ListDataPointsRequest* /*request*/, ::thingspect::api::ListDataPointsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListDataPoints(::grpc::ServerContext* context, ::thingspect::api::ListDataPointsRequest* request, ::grpc::ServerAsyncResponseWriter< ::thingspect::api::ListDataPointsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_LatestDataPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_LatestDataPoints() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_LatestDataPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LatestDataPoints(::grpc::ServerContext* /*context*/, const ::thingspect::api::LatestDataPointsRequest* /*request*/, ::thingspect::api::LatestDataPointsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLatestDataPoints(::grpc::ServerContext* context, ::thingspect::api::LatestDataPointsRequest* request, ::grpc::ServerAsyncResponseWriter< ::thingspect::api::LatestDataPointsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PublishDataPoints<WithAsyncMethod_ListDataPoints<WithAsyncMethod_LatestDataPoints<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_PublishDataPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PublishDataPoints() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::thingspect::api::PublishDataPointsRequest, ::google::protobuf::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::thingspect::api::PublishDataPointsRequest* request, ::google::protobuf::Empty* response) { return this->PublishDataPoints(context, request, response); }));}
    void SetMessageAllocatorFor_PublishDataPoints(
        ::grpc::MessageAllocator< ::thingspect::api::PublishDataPointsRequest, ::google::protobuf::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::thingspect::api::PublishDataPointsRequest, ::google::protobuf::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PublishDataPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PublishDataPoints(::grpc::ServerContext* /*context*/, const ::thingspect::api::PublishDataPointsRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PublishDataPoints(
      ::grpc::CallbackServerContext* /*context*/, const ::thingspect::api::PublishDataPointsRequest* /*request*/, ::google::protobuf::Empty* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListDataPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListDataPoints() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::thingspect::api::ListDataPointsRequest, ::thingspect::api::ListDataPointsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::thingspect::api::ListDataPointsRequest* request, ::thingspect::api::ListDataPointsResponse* response) { return this->ListDataPoints(context, request, response); }));}
    void SetMessageAllocatorFor_ListDataPoints(
        ::grpc::MessageAllocator< ::thingspect::api::ListDataPointsRequest, ::thingspect::api::ListDataPointsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::thingspect::api::ListDataPointsRequest, ::thingspect::api::ListDataPointsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListDataPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListDataPoints(::grpc::ServerContext* /*context*/, const ::thingspect::api::ListDataPointsRequest* /*request*/, ::thingspect::api::ListDataPointsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListDataPoints(
      ::grpc::CallbackServerContext* /*context*/, const ::thingspect::api::ListDataPointsRequest* /*request*/, ::thingspect::api::ListDataPointsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_LatestDataPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_LatestDataPoints() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::thingspect::api::LatestDataPointsRequest, ::thingspect::api::LatestDataPointsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::thingspect::api::LatestDataPointsRequest* request, ::thingspect::api::LatestDataPointsResponse* response) { return this->LatestDataPoints(context, request, response); }));}
    void SetMessageAllocatorFor_LatestDataPoints(
        ::grpc::MessageAllocator< ::thingspect::api::LatestDataPointsRequest, ::thingspect::api::LatestDataPointsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::thingspect::api::LatestDataPointsRequest, ::thingspect::api::LatestDataPointsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_LatestDataPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LatestDataPoints(::grpc::ServerContext* /*context*/, const ::thingspect::api::LatestDataPointsRequest* /*request*/, ::thingspect::api::LatestDataPointsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* LatestDataPoints(
      ::grpc::CallbackServerContext* /*context*/, const ::thingspect::api::LatestDataPointsRequest* /*request*/, ::thingspect::api::LatestDataPointsResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_PublishDataPoints<WithCallbackMethod_ListDataPoints<WithCallbackMethod_LatestDataPoints<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_PublishDataPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PublishDataPoints() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PublishDataPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PublishDataPoints(::grpc::ServerContext* /*context*/, const ::thingspect::api::PublishDataPointsRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListDataPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListDataPoints() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ListDataPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListDataPoints(::grpc::ServerContext* /*context*/, const ::thingspect::api::ListDataPointsRequest* /*request*/, ::thingspect::api::ListDataPointsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_LatestDataPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_LatestDataPoints() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_LatestDataPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LatestDataPoints(::grpc::ServerContext* /*context*/, const ::thingspect::api::LatestDataPointsRequest* /*request*/, ::thingspect::api::LatestDataPointsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_PublishDataPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PublishDataPoints() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_PublishDataPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PublishDataPoints(::grpc::ServerContext* /*context*/, const ::thingspect::api::PublishDataPointsRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPublishDataPoints(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListDataPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListDataPoints() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ListDataPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListDataPoints(::grpc::ServerContext* /*context*/, const ::thingspect::api::ListDataPointsRequest* /*request*/, ::thingspect::api::ListDataPointsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListDataPoints(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_LatestDataPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_LatestDataPoints() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_LatestDataPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LatestDataPoints(::grpc::ServerContext* /*context*/, const ::thingspect::api::LatestDataPointsRequest* /*request*/, ::thingspect::api::LatestDataPointsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLatestDataPoints(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PublishDataPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PublishDataPoints() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PublishDataPoints(context, request, response); }));
    }
    ~WithRawCallbackMethod_PublishDataPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PublishDataPoints(::grpc::ServerContext* /*context*/, const ::thingspect::api::PublishDataPointsRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PublishDataPoints(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListDataPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListDataPoints() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListDataPoints(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListDataPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListDataPoints(::grpc::ServerContext* /*context*/, const ::thingspect::api::ListDataPointsRequest* /*request*/, ::thingspect::api::ListDataPointsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListDataPoints(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_LatestDataPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_LatestDataPoints() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->LatestDataPoints(context, request, response); }));
    }
    ~WithRawCallbackMethod_LatestDataPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LatestDataPoints(::grpc::ServerContext* /*context*/, const ::thingspect::api::LatestDataPointsRequest* /*request*/, ::thingspect::api::LatestDataPointsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* LatestDataPoints(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PublishDataPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PublishDataPoints() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::thingspect::api::PublishDataPointsRequest, ::google::protobuf::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::thingspect::api::PublishDataPointsRequest, ::google::protobuf::Empty>* streamer) {
                       return this->StreamedPublishDataPoints(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PublishDataPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PublishDataPoints(::grpc::ServerContext* /*context*/, const ::thingspect::api::PublishDataPointsRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPublishDataPoints(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::thingspect::api::PublishDataPointsRequest,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListDataPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListDataPoints() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::thingspect::api::ListDataPointsRequest, ::thingspect::api::ListDataPointsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::thingspect::api::ListDataPointsRequest, ::thingspect::api::ListDataPointsResponse>* streamer) {
                       return this->StreamedListDataPoints(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListDataPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListDataPoints(::grpc::ServerContext* /*context*/, const ::thingspect::api::ListDataPointsRequest* /*request*/, ::thingspect::api::ListDataPointsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListDataPoints(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::thingspect::api::ListDataPointsRequest,::thingspect::api::ListDataPointsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_LatestDataPoints : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_LatestDataPoints() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::thingspect::api::LatestDataPointsRequest, ::thingspect::api::LatestDataPointsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::thingspect::api::LatestDataPointsRequest, ::thingspect::api::LatestDataPointsResponse>* streamer) {
                       return this->StreamedLatestDataPoints(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_LatestDataPoints() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status LatestDataPoints(::grpc::ServerContext* /*context*/, const ::thingspect::api::LatestDataPointsRequest* /*request*/, ::thingspect::api::LatestDataPointsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedLatestDataPoints(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::thingspect::api::LatestDataPointsRequest,::thingspect::api::LatestDataPointsResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_PublishDataPoints<WithStreamedUnaryMethod_ListDataPoints<WithStreamedUnaryMethod_LatestDataPoints<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_PublishDataPoints<WithStreamedUnaryMethod_ListDataPoints<WithStreamedUnaryMethod_LatestDataPoints<Service > > > StreamedService;
};

}  // namespace api
}  // namespace thingspect


#endif  // GRPC_api_2fthingspect_5fdatapoint_2eproto__INCLUDED
