<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mqtt/thingspect_payload.proto

namespace GPBMetadata\Mqtt;

class ThingspectPayload
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\ThingspectDatapoint::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xA7\x01\x0A\x1Dmqtt/thingspect_payload.proto\x12\x0Fthingspect.mqtt\"F\x0A\x07Payload\x12,\x0A\x06points\x18\x01 \x03(\x0B2\x1C.thingspect.common.DataPoint\x12\x0D\x0A\x05token\x18\x02 \x01(\x09B%Z#github.com/thingspect/proto/go/mqttb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

