# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/device.proto

require 'common/device_pb'
require 'google/protobuf/empty_pb'
require 'google/protobuf/field_mask_pb'
require 'google/api/annotations_pb'
require 'google/api/field_behavior_pb'
require 'protoc-gen-openapiv2/options/annotations_pb'
require 'validate/validate_pb'
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("api/device.proto", :syntax => :proto3) do
    add_message "thingspect.api.CreateDeviceRequest" do
      optional :device, :message, 1, "thingspect.common.Device"
    end
    add_message "thingspect.api.CreateDeviceLoRaWANRequest" do
      optional :id, :string, 1
      oneof :type_oneof do
        optional :gateway_lorawan_type, :message, 2, "thingspect.api.CreateDeviceLoRaWANRequest.GatewayLoRaWANType", json_name: "gatewayLoRaWANType"
        optional :device_lorawan_type, :message, 3, "thingspect.api.CreateDeviceLoRaWANRequest.DeviceLoRaWANType", json_name: "deviceLoRaWANType"
      end
    end
    add_message "thingspect.api.CreateDeviceLoRaWANRequest.GatewayLoRaWANType" do
    end
    add_message "thingspect.api.CreateDeviceLoRaWANRequest.DeviceLoRaWANType" do
      optional :app_key, :string, 1
    end
    add_message "thingspect.api.GetDeviceRequest" do
      optional :id, :string, 1
    end
    add_message "thingspect.api.UpdateDeviceRequest" do
      optional :device, :message, 1, "thingspect.common.Device"
      optional :update_mask, :message, 2, "google.protobuf.FieldMask"
    end
    add_message "thingspect.api.DeleteDeviceLoRaWANRequest" do
      optional :id, :string, 1
    end
    add_message "thingspect.api.DeleteDeviceRequest" do
      optional :id, :string, 1
    end
    add_message "thingspect.api.ListDevicesRequest" do
      optional :page_size, :int32, 1
      optional :page_token, :string, 2
      optional :tag, :string, 3
    end
    add_message "thingspect.api.ListDevicesResponse" do
      repeated :devices, :message, 1, "thingspect.common.Device"
      optional :next_page_token, :string, 2
      optional :total_size, :int32, 3
    end
  end
end

module Thingspect
  module Api
    CreateDeviceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("thingspect.api.CreateDeviceRequest").msgclass
    CreateDeviceLoRaWANRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("thingspect.api.CreateDeviceLoRaWANRequest").msgclass
    CreateDeviceLoRaWANRequest::GatewayLoRaWANType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("thingspect.api.CreateDeviceLoRaWANRequest.GatewayLoRaWANType").msgclass
    CreateDeviceLoRaWANRequest::DeviceLoRaWANType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("thingspect.api.CreateDeviceLoRaWANRequest.DeviceLoRaWANType").msgclass
    GetDeviceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("thingspect.api.GetDeviceRequest").msgclass
    UpdateDeviceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("thingspect.api.UpdateDeviceRequest").msgclass
    DeleteDeviceLoRaWANRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("thingspect.api.DeleteDeviceLoRaWANRequest").msgclass
    DeleteDeviceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("thingspect.api.DeleteDeviceRequest").msgclass
    ListDevicesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("thingspect.api.ListDevicesRequest").msgclass
    ListDevicesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("thingspect.api.ListDevicesResponse").msgclass
  end
end
