# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: api/thingspect_user.proto for package 'thingspect.api'

require 'grpc'
require 'api/thingspect_user_pb'

module Thingspect
  module Api
    module UserService
      # UserService contains functions to query and modify users.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'thingspect.api.UserService'

        # Create a user. Users can log in and use the Atlas API and Thingspect website based on the limits of their role.
        rpc :CreateUser, ::Thingspect::Api::CreateUserRequest, ::Thingspect::Api::User
        # Get a user by ID. Users can log in and use the Atlas API and Thingspect website based on the limits of their role.
        rpc :GetUser, ::Thingspect::Api::GetUserRequest, ::Thingspect::Api::User
        # Update a user. Users can log in and use the Atlas API and Thingspect website based on the limits of their role.
        rpc :UpdateUser, ::Thingspect::Api::UpdateUserRequest, ::Thingspect::Api::User
        # Update a user's password. Passwords are checked against NIST password guidelines.
        rpc :UpdateUserPassword, ::Thingspect::Api::UpdateUserPasswordRequest, ::Google::Protobuf::Empty
        # Delete a user by ID. Users can log in and use the Atlas API and Thingspect website based on the limits of their role.
        rpc :DeleteUser, ::Thingspect::Api::DeleteUserRequest, ::Google::Protobuf::Empty
        # List users. Users can log in and use the Atlas API and Thingspect website based on the limits of their role.
        rpc :ListUsers, ::Thingspect::Api::ListUsersRequest, ::Thingspect::Api::ListUsersResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
