# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: api/thingspect_device.proto for package 'thingspect.api'

require 'grpc'
require 'api/thingspect_device_pb'

module Thingspect
  module Api
    module DeviceService
      # DeviceService contains functions to query and modify devices.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'thingspect.api.DeviceService'

        # Create a device. Devices generate data points.
        rpc :CreateDevice, ::Thingspect::Api::CreateDeviceRequest, ::Thingspect::Api::Device
        # Add LoRaWAN configuration to a device.
        rpc :CreateDeviceLoRaWAN, ::Thingspect::Api::CreateDeviceLoRaWANRequest, ::Google::Protobuf::Empty
        # Get a device by ID. Devices generate data points.
        rpc :GetDevice, ::Thingspect::Api::GetDeviceRequest, ::Thingspect::Api::Device
        # Update a device. Devices generate data points.
        rpc :UpdateDevice, ::Thingspect::Api::UpdateDeviceRequest, ::Thingspect::Api::Device
        # Remove LoRaWAN configuration from a device.
        rpc :DeleteDeviceLoRaWAN, ::Thingspect::Api::DeleteDeviceLoRaWANRequest, ::Google::Protobuf::Empty
        # Delete a device by ID. Devices generate data points.
        rpc :DeleteDevice, ::Thingspect::Api::DeleteDeviceRequest, ::Google::Protobuf::Empty
        # List all devices. Devices generate data points.
        rpc :ListDevices, ::Thingspect::Api::ListDevicesRequest, ::Thingspect::Api::ListDevicesResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
